name: Periodic health check

on:
  # schedule:
    # - cron: '47 * 2,3,4 7 *'
  push:
    branches: 
      - main
      
jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-884y.onrender.com
          max-attempts: 3
          retry-delay: 5s
